/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    Button: typeof import('./src/components/Button.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderConf: typeof import('./src/components/HeaderConf.vue')['default']
    HeaderContext: typeof import('./src/components/HeaderContext.vue')['default']
    HeaderProvide: typeof import('./src/components/HeaderProvide.vue')['default']
    HeaderVisibleConf: typeof import('./src/components/HeaderVisibleConf.vue')['default']
    HeaderVisibleContext: typeof import('./src/components/HeaderVisibleContext.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MessageConent: typeof import('./src/components/MessageConent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/Sider.vue')['default']
  }
}
